name: Android Feature Branch CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - develop
      
jobs:
  build:
      name: Build and Run
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2.3.4
      - name: set up JDK 1.8
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: sudo bash ./gradlew build
      - name: Build debug APK
        run: sudo bash ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v2.2.1
        with:
            name: app
            path: app/build/outputs/apk/debug
